# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# export python requirements
- repo: https://github.com/pdm-project/pdm
  rev: 2.18.1
  hooks:
    - id: pdm-export
      # command arguments, e.g.:
      args: ['-o', 'requirements.txt', '--without-hashes']
      files: ^pdm.lock$

- repo: https://github.com/pdm-project/pdm
  rev: 2.18.1
  hooks:
    - id: pdm-lock-check

- repo: https://github.com/pdm-project/pdm
  rev: 2.18.1
  hooks:
    - id: pdm-sync
      additional_dependencies:
        - keyring
